import { MY_CARD_NOIR_GRADIENT } from "@/lib/cardSkins";
import { DEMO_USER_EMAIL, DEMO_USER_FULL_NAME } from "@/config/demo-user";

export const MOCK_USER = {
    id: "db01a59c-a418-4da0-a4aa-fb032d500b04",
    email: DEMO_USER_EMAIL,
    fullName: DEMO_USER_FULL_NAME,
    kycStatus: "approved"
};

export const MOCK_CARDS = [
    {
        id: "c1",
 // Full PAN needed for on-card reveal; masked UI still shows •••• + last4
        cardNumber: "4532 0198 7741 1234",
        cardHolder: DEMO_USER_FULL_NAME,
        expiryDate: "12/28",
        cardType: "VISA",
        gradient: MY_CARD_NOIR_GRADIENT,
        cardColor: "#151313",
        cardName: "My Card",
        balance: 2800.88,
        isActive: true,
        isLocked: false,
        dailyLimit: 2000,
        cvv: "047",
    },
    {
        id: "c2",
        cardNumber: "5500 0000 0000 5678",
        cardHolder: DEMO_USER_FULL_NAME,
        expiryDate: "06/27",
        cardType: "MASTERCARD",
        gradient: "linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%)",
        cardColor: "#1e3a72",
        cardName: "Ad Spending",
        balance: 520.42,
        isActive: true,
        isLocked: true,
        dailyLimit: 500,
        cvv: "218",
    },
    {
        id: "c3",
        cardNumber: "4012 8888 8888 3456",
        cardHolder: DEMO_USER_FULL_NAME,
        expiryDate: "03/29",
        cardType: "VISA",
        gradient: "linear-gradient(135deg, #4c1d95 0%, #8b5cf6 100%)",
        cardColor: "#4c1d95",
        cardName: "Reserve",
        balance: 412.18,
        isActive: true,
        isLocked: false,
        dailyLimit: 1500,
        cvv: "093",
    },
];

export const MOCK_TRANSACTIONS = [
    {
        id: "t1",
        name: "Apple Store",
        type: "cardPayment",
        amount: 1299.00,
        isIncoming: false,
        category: "shopping",
        date: new Date().toISOString(),
        status: "completed",
        cardId: "c1"
    },
    {
        id: "t2",
        name: "USDC Deposit",
        type: "directDeposit",
        amount: 2500.00,
        isIncoming: true,
        category: "income",
        date: new Date(Date.now() - 86400000).toISOString(),
        status: "completed",
        cardId: "c1"
    },
    {
        id: "t3",
        name: "Uber",
        type: "cardPayment",
        amount: 24.5,
        isIncoming: false,
        category: "transport",
        date: new Date(Date.now() - 86400000 * 2).toISOString(),
        status: "completed",
        cardId: "c1",
    },
    {
        id: "t4",
        name: "Netflix",
        type: "subscription",
        amount: 19.99,
        isIncoming: false,
        category: "entertainment",
        date: new Date(Date.now() - 86400000 * 3).toISOString(),
        status: "completed",
        cardId: "c1",
    },
    {
        id: "t5",
        name: "Whole Foods",
        type: "cardPayment",
        amount: 86.42,
        isIncoming: false,
        category: "shopping",
        date: new Date(Date.now() - 86400000 * 4).toISOString(),
        status: "completed",
        cardId: "c1",
    },
    {
        id: "t6",
        name: "Payroll",
        type: "directDeposit",
        amount: 4200.0,
        isIncoming: true,
        category: "income",
        date: new Date(Date.now() - 86400000 * 5).toISOString(),
        status: "completed",
        cardId: "c1",
    },
    {
        id: "t7",
        name: "Shell Gas",
        type: "cardPayment",
        amount: 58.17,
        isIncoming: false,
        category: "transport",
        date: new Date(Date.now() - 86400000 * 6).toISOString(),
        status: "completed",
        cardId: "c1",
    },
    {
        id: "t8",
        name: "Spotify",
        type: "subscription",
        amount: 11.99,
        isIncoming: false,
        category: "entertainment",
        date: new Date(Date.now() - 86400000 * 7).toISOString(),
        status: "completed",
        cardId: "c1",
    },
    {
        id: "t9",
        name: "Amazon",
        type: "cardPayment",
        amount: 142.35,
        isIncoming: false,
        category: "shopping",
        date: new Date(Date.now() - 86400000 * 8).toISOString(),
        status: "completed",
        cardId: "c1",
    },
    {
        id: "t10",
        name: "USDC Deposit",
        type: "directDeposit",
        amount: 750.0,
        isIncoming: true,
        category: "income",
        date: new Date(Date.now() - 86400000 * 9).toISOString(),
        status: "completed",
        cardId: "c1",
    },
    {
        id: "t11",
        name: "Delta Airlines",
        type: "cardPayment",
        amount: 312.8,
        isIncoming: false,
        category: "transport",
        date: new Date(Date.now() - 86400000 * 10).toISOString(),
        status: "completed",
        cardId: "c1",
    },
    {
        id: "t12",
        name: "Starbucks",
        type: "cardPayment",
        amount: 6.85,
        isIncoming: false,
        category: "shopping",
        date: new Date(Date.now() - 86400000 * 11).toISOString(),
        status: "completed",
        cardId: "c1",
    },
    {
        id: "t13",
        name: "GitHub",
        type: "subscription",
        amount: 4.0,
        isIncoming: false,
        category: "entertainment",
        date: new Date(Date.now() - 86400000 * 12).toISOString(),
        status: "completed",
        cardId: "c1",
    },
    {
        id: "t14",
        name: "Venmo Transfer",
        type: "bankTransfer",
        amount: 200.0,
        isIncoming: true,
        category: "income",
        date: new Date(Date.now() - 86400000 * 13).toISOString(),
        status: "completed",
        cardId: "c1",
    },
    {
        id: "t15",
        name: "Target",
        type: "cardPayment",
        amount: 67.29,
        isIncoming: false,
        category: "shopping",
        date: new Date(Date.now() - 86400000 * 14).toISOString(),
        status: "completed",
        cardId: "c1",
    },
    {
        id: "t16",
        name: "Lyft",
        type: "cardPayment",
        amount: 18.4,
        isIncoming: false,
        category: "transport",
        date: new Date(Date.now() - 86400000 * 15).toISOString(),
        status: "completed",
        cardId: "c1",
    },
    {
        id: "t17",
        name: "HBO Max",
        type: "subscription",
        amount: 16.99,
        isIncoming: false,
        category: "entertainment",
        date: new Date(Date.now() - 86400000 * 16).toISOString(),
        status: "completed",
        cardId: "c1",
    },
    {
        id: "t18",
        name: "Wire Transfer",
        type: "bankTransfer",
        amount: 1500.0,
        isIncoming: true,
        category: "income",
        date: new Date(Date.now() - 86400000 * 17).toISOString(),
        status: "completed",
        cardId: "c1",
    },
    {
        id: "t19",
        name: "CVS Pharmacy",
        type: "cardPayment",
        amount: 32.15,
        isIncoming: false,
        category: "shopping",
        date: new Date(Date.now() - 86400000 * 18).toISOString(),
        status: "completed",
        cardId: "c1",
    },
    {
        id: "t20",
        name: "OpenAI",
        type: "subscription",
        amount: 20.0,
        isIncoming: false,
        category: "entertainment",
        date: new Date(Date.now() - 86400000 * 19).toISOString(),
        status: "completed",
        cardId: "c1",
    },
];

/** Upcoming widget - developer subscriptions (debits only). */
export const MOCK_UPCOMING_TRANSACTIONS = [
    {
        id: "up1",
        name: "Claude Max",
        type: "recurringPayment",
        amount: 100.0,
        isIncoming: false,
        category: "entertainment",
        date: new Date(Date.now() + 86400000 * 5).toISOString(),
        status: "pending",
        cardId: "c1",
    },
    {
        id: "up2",
        name: "Supabase",
        type: "recurringPayment",
        amount: 25.0,
        isIncoming: false,
        category: "utilities",
        date: new Date(Date.now() + 86400000 * 12).toISOString(),
        status: "pending",
        cardId: "c1",
    },
    {
        id: "up3",
        name: "Framer",
        type: "recurringPayment",
        amount: 30.0,
        isIncoming: false,
        category: "entertainment",
        date: new Date(Date.now() + 86400000 * 18).toISOString(),
        status: "pending",
        cardId: "c1",
    },
];

export const MOCK_NOTIFICATIONS = [
    {
        id: "n1",
        title: "Transaction Successful",
        message: "Your deposit of 2500 USDC has been credited.",
        type: "transaction",
        is_read: false,
        created_at: new Date().toISOString()
    },
    {
        id: "n2",
        title: "Security Alert",
        message: "New login detected from unusual IP.",
        type: "security",
        is_read: true,
        created_at: new Date(Date.now() - 3600000).toISOString()
    }
];
